Dev
danieltichiyama/the-async-force-ep-1 pull request #1
Opened 2019-07-26 04:18 UTC by danieltichiyama

2019-07-26 04:36 UTC, taesup requested changes

2019-07-26 04:36 UTC, taesup commented on js/app.js
> +    let randomH3 = document.createElement("h3");
Choose a better variable name

2019-07-26 05:43 UTC, danieltichiyama commented on js/app.js
> +    let randomH3 = document.createElement("h3");
variable name changed, ready for review

2019-07-26 07:15 UTC, taesup requested changes

2019-07-26 07:15 UTC, taesup commented on js/app.js
> +    let superAwesomeAndYetStillRandomH3 = document.createElement("h3");
no. change it.

2019-07-27 19:54 UTC, danieltichiyama commented on js/app.js
> +    let superAwesomeAndYetStillRandomH3 = document.createElement("h3");
okay... fine... done :(

2019-07-27 19:58 UTC, taesup approved these changes

2019-07-27 19:59 UTC, merged